### PR TITLE
1177 10.3.6 release notes

### PR DESCRIPTION
**Pull request by kirstiaa**
Added a long description on new follow-up with link to Learn|Docs.
A small change for Request and then there is a new version of Mobile CRM.

Hope that is all and all is correct.

### CODE REVIEW

**Comment by kirstiaa** [comment]
I tried to fix some heading spelling errors straight inside github, but that was not successful...
So I did the last heading change inside VS, but not sure if it was a good idea.

Sorry about this.

**Review by digitaldiina — CHANGES_REQUESTED** [review]
@kirstiaa would you be so kind and compress the screenshots with tinypng? They are huge, especially the mobile ones.

**Comment by kirstiaa** [comment]
@digitaldiina Release notes 10.3.6 are ready for review.
Sorry about the delay, I did not see the wish for compressed images.

**Review by digitaldiina — APPROVED** [review]

**Comment by kirstiaa** [comment]
@digitaldiina I see in the published version of 10.3.6 you have changed favourites to favorites.
It has been decided that we aim to use British English in our text both in Release notes and the Learn content. Please do not change to American English, I try to keep it British English.
If you do not agree with this, take it to a higher level.

**Pull request merged**
