### PR TITLE
Add separate page for request template variables and add the new ticket message id variable

### PR DESCRIPTION
**Pull request by acdavidh**
see https://github.com/SuperOfficeDocs/superoffice-docs/issues/671

Not sure how to handle that ticket message id is only available starting in 10.2.5?

### CODE REVIEW

**Comment by SuperOfficeDevNet** [comment]
This is a very nice suggestion! 👍

**Review by SuperOfficeDevNet — APPROVED** [review]

**Comment by SuperOfficeDevNet** [comment]
@acdavidh Where did your thoughts about <miid> come from? I don't find that in the TemplateVariable source anywhere...

**Comment by acdavidh** [comment]
> @acdavidh Where did your thoughts about come from? I don't find that in the TemplateVariable source anywhere...

I got the miid variable from a comment on my wish
https://community.superoffice.com/nl/product-releases/bugs-wishes/product-issue/?bid=38924&azure=1

**Comment by SuperOfficeDevNet** [comment]
@acdavidh OK, thanks! After a bit of digging, looks like it's only going to be available in web panel URLs (via SCIL) and not the standard TemplateVariable parsing routines... :-( 

I'll annotate that in the docs.

**Comment by acdavidh** [comment]
> @acdavidh OK, thanks! After a bit of digging, looks like it's only going to be available in web panel URLs (via SCIL) and not the standard TemplateVariable parsing routines... :-(
> 
> I'll annotate that in the docs.

Thanks for the clarification, that's a shame! hopefully now the the merging of service and crm additionele template variables will be made available for request/ticket and ticket message

**Pull request merged**
