### PR TITLE
#225 added documentation for new triggers

### PR DESCRIPTION
**Pull request by kronicz**
Closing #225

### CODE REVIEW

**Comment by digitaldiina** [comment]
@kronicz I pushed an update with a few tweaks:

- Alphabetical sort order in the child listing
- Don't n need to escape brackets in normal text
- Added `<p></p> to create linebreak before input value tables
- Removed bold "Note: " since it is already in a remark.

**Comment by digitaldiina** [comment]
@kronicz the **ScreenChooserType Enum** is generated from source code and your changes will not survive the next build. You can identify this by looking for `so.generated: true` in the metadata at the top of the file.

The update should be done in the code. Might be there already and just need a fresh database build. @SuperOfficeDevNet ?

The trigger reference is good to merge once we sort the enum situation out.

**Comment by kronicz** [comment]
> @kronicz the **ScreenChooserType Enum** is generated from source code and your changes will not survive the next build. You can identify this by looking for `so.generated: true` in the metadata at the top of the file.
> 
> The update should be done in the code. Might be there already and just need a fresh database build. @SuperOfficeDevNet ?
> 
> The trigger reference is good to merge once we sort the enum situation out.

Could we perhaps just revert this related to Enum to be able to merge it? Not sure if something must be done in modelling if that is the source?

**Comment by SuperOfficeDevNet** [comment]
Hi @kronicz! 
New events should be add to the [CRMScript.NetServer.EventHandlerType](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/automation/crmscript/reference/CRMScript.NetServer.EventHandlerType.yml) file, not the [screenchoosertype](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/database/tables/enums/screenchoosertype.md) file. 

These are two completely different things, are they not?

**Pull request merged**
