### PR TITLE
Develop/efasting/add quickstart

### PR DESCRIPTION
**Pull request by ejfasting**

### CODE REVIEW

**Review by digitaldiina — CHANGES_REQUESTED** [review]
- The tab IDs must be unique inside the file. For example, `#tab/interactive1`, `#tab/interactive2`
- All new pages must be added to the toc.yml file in the location they should be shown
- Use relative links to content on docs, either to the .md or .yml file or the uid found inside a yml api reference. For example *../PATH/v1AppointmentEntity_PostAppointmentEntity.md*

@ejfasting could you fix this, and I'll edit and apply inline formatting

**Review by SuperOfficeDevNet — CHANGES_REQUESTED** [review]
The content is well-written, but I've identified a few potential areas for improvement in terms of grammar, clarity, and consistency:

1. **Consistency in Terminology**:
   - The term "REST api" is sometimes written as "REST API". It's best to maintain consistency. I recommend using "REST API" throughout the document.

2. **Spelling and Grammar**:
   - "This quickstart will focus on how you can get up and running using the REST api, which is available for both online and onsite (from version XXXX for onsite)." 
     - "api" should be "API".
     - Placeholder "XXXX" should be replaced with the actual version number.
   - "Which flow you select depends on what your application does, but on the most basic level you have the interactive flow, where a SuperOffice-user inputs their credentials, or a non-interactive flow, where no interaction is required."
     - Consider rephrasing for clarity: "The flow you select depends on your application's requirements. At the most basic level, there's the interactive flow, where a SuperOffice user inputs their credentials, and the non-interactive flow, which requires no user interaction."
   - "We try to keep the examples up to date, but as things change without our knowledge we are depending on feedback from you, as the users/readers of the examples, to be able to fix things if they are not working."
     - Consider rephrasing for clarity: "We strive to keep the examples updated. However, as changes might occur without our knowledge, we rely on your feedback to address any issues."
   - "We do not recommend you do it one way or another, and its totally up to what you find most efficient in your workflow."
     - "its" should be "it's".
   - "Which REST-api you chose to use is up to you, and you dont need to only use one or the other as they can be used interchangeably."
     - "REST-api" should be "REST API".
     - "dont" should be "don't".
   - "The returner json is the whole, updated, AppointmentEntity:"
     - "returner" should be "returned".
   - "This example shows howto:"
     - "howto" should be "how to".
   - "In the example above we get a lot of extra data that we dont really need."
     - "dont" should be "don't".
   - "You can filder the payload by adding queryparameters to your uri."
     - "filder" should be "filter".
     - "queryparameters" should be "query parameters".
     - "uri" should be "URI".

3. **Clarity**:
   - "The description for how you run each authentication flow is heavily documented already, and this article will not contain specifics about how you get a hold of the ticket itself."
     - Consider rephrasing for clarity: "The process for executing each authentication flow is already well-documented. This article won't delve into the specifics of obtaining the ticket."

4. **Formatting**:
   - Ensure that placeholders like "{{environment}}" and "{{tenant}}" are meant to be there and are clear to the reader.
   - Ensure that all referenced links at the bottom are correctly linked in the main content.

5. **Technical Accuracy**:
   - Ensure that all code snippets, API endpoints, and technical details are accurate and up-to-date.

Overall, the content is comprehensive and provides a lot of valuable information.

**Review by digitaldiina — DISMISSED** [review]

**Comment by digitaldiina** [comment]
I cut the following text because it doesn't belong in a quick-start guide. It should be in the examples' repo.

> We strive to keep the examples updated. However, as changes might occur without our knowledge, we rely on your feedback to address any issues. Feel free to create an issue whenever you come across something that is not working as intended!

**Review by digitaldiina — COMMENTED** [review]
I've revised the new page rather extensively. With emphasis on **quick** start, we shouldn't bother readers with excess words.

One question: do we need to include `"UpdatedBy": null` in the JSON responses? It might confuse some since it's still null after the patch.

**Review by SuperOfficeDevNet — APPROVED** [review]

**Pull request merged**
