### PR TITLE
Add Windows 11 and SuperOffice 10 to Sys requirements

### PR DESCRIPTION
**Pull request by pavlas77**

### CODE REVIEW

**Review by digitaldiina — COMMENTED** [review]
Not a deal-breaker, but I would strongly advise you to improve on the following:

- Don't use `&nbsp;`, it makes searching the source for specific terms hard
- Stay consistent: either say *version x and newer" or list all versions. Don't mix the two
- Group versions in column headings consistently: for example, either list 9.1 and 9.2 separately or combine as 9. Combine columns where possible to reduce page load time and make it easier to scan the info

**Comment by pavlas77** [comment]
Thank you for your comments

- &nbsp; was a legacy code from EPI where I had to use it to get some decent styling and I haven't noticed it untill you pointed it out now. It has been removed.
- *version x and newer" - do you see a mix of the two styles anywhere? May be I overlooked something but the places I checked had all "version 8.5 and newer"
- in all tables 9.1 and 9.2 is listed separately, apart from the list of service endpoints where it says only 9. Is this what you mean, or are there any other places?
- grouping of columns: I'd like to list all main releases separately but sometimes I need to split it to more detailed info for specific SR. I see 9.1 and 9.2 could be combined into one column as 9 branch is closed and there won't be any news there. Can we leave it for next round? I'll be adding new macOS and Windows Server 2022 to the tables soon so I can combine 9 into one at that time.

**Comment by digitaldiina** [comment]
The CRM server and IIS requirements have H1 (and description) that do not follow the version x and newer pattern. 
I noticed that you started using 9 as a bucket and thought it would make sense to do it throughout.
I'm not talking about sacrificing clarity where there are differences. But if we for example look at the database compatibility table, 8.1, 8.2, 8.3, and 8.4 are identical and could benefit from a merge.
It is ok to leave the improvements for the next round. Let Tony know when you are ready to merge (I'll be out of office).

**Comment by pavlas77** [comment]
I fixed the H1 and descriotion and some thoer places, all should say 8 and newer now.

Will look at the version 9 and the column merge in the next round of edits. Agree database table columns could be merged.

**Review by SuperOfficeDevNet — APPROVED** [review]
Looks much better, and should age well. Nice work!

**Pull request merged**
