### PR TITLE
325 sharepoint documents

### PR DESCRIPTION
**Pull request by pavlas77**

### CODE REVIEW

**Comment by pavlas77** [comment]
Hi @digitaldiina, I did as much as I can do now. 

Not sure about this point: Rewrite g-suite content after incorporating the configuration page. - the new config page doesn't interfere with the original Google document templates configuration, which is still ok.

I see we will need some roundtrips to get this approved.

**Comment by digitaldiina** [comment]
@martin I merged in from main to get the latest updates, which was quite a lot. That took care of the merge conflicts.

Let me know if the result was as expected and then I'll start reviewing the content and formatting.

**Comment by pavlas77** [comment]
@digitaldiina All seems to be OK after the merge from main.

**Comment by digitaldiina** [comment]
I fixed a few issues with the formatting.

https://github.com/SuperOfficeDocs/contribution/blob/main/markdown-guide/markdownlint.md (to go live soon)

**Review by digitaldiina — CHANGES_REQUESTED** [review]
- All images should have descriptive alt text. Please update those that have only `[x -screenshot]`
- Links in index.yml are breaking. Should be .md and not .html
- Headings should be 80 characters or less. Please shorten these:

superoffice-docs/docs/document/cloud/legacy/office-365/troubleshooting.md:57:81 MD013/line-length Line length [Expected: 80; Actual: 101]
superoffice-docs/docs/document/cloud/overview.md:13:81 MD013/line-length Line length [Expected: 80; Actual: 87]
superoffice-docs/docs/document/cloud/sharepoint-documents/configure-templates.md:75:81 MD013/line-length Line length [Expected: 80; Actual: 93]
superoffice-docs/docs/document/cloud/sharepoint-documents/configure-templates.md:82:81 MD013/line-length Line length [Expected: 80; Actual: 103]
superoffice-docs/docs/document/cloud/sharepoint-documents/troubleshooting.md:15:81 MD013/line-length Line length [Expected: 80; Actual: 89]
superoffice-docs/docs/document/cloud/sharepoint-documents/troubleshooting.md:33:81 MD013/line-length Line length [Expected: 80; Actual: 148]
superoffice-docs/docs/document/templates/troubleshooting.md:91:121 MD013/line-length Line length [Expected: 120; Actual: 146]

**Comment by digitaldiina** [comment]
@pavlas77 consider adding a tile for SharePoint documents to the document category page for extra visibility of the new material

**Review by digitaldiina — APPROVED** [review]
Great, thanks for the patience, @pavlas77 !

**Pull request merged**
