### PR TITLE
128 update omt screenshots

### PR DESCRIPTION
**Pull request by pavlas77**

### CODE REVIEW

**Comment by pavlas77** [comment]
I tried to add issue 128 to the Development, but it doesnt not come up in the list.

**Comment by digitaldiina** [comment]
Thanks for retaking all the screenshots and improving the file names, @pavlas77 . This builds ok, but I'd like @MargretheR to weigh in on this on Monday before merging to main.

The new order-sandbox page should be added to the toc.

**Comment by digitaldiina** [comment]
@pavlas77 can you please fix it according to the feedback from @MargretheR ?

**Comment by pavlas77** [comment]
@MargretheR @digitaldiina ready for review

**Comment by digitaldiina** [comment]
Thanks @pavlas77 and @MargretheR :)

**Pull request merged**
