### PR TITLE
260 separate ribbons mailink

### PR DESCRIPTION
**Pull request by pavlas77**

### CODE REVIEW

**Comment by pavlas77** [comment]
@digitaldiina This is a slightly bigger change, I tried to use include files. Your comments are welcome.

**Review by digitaldiina — CHANGES_REQUESTED** [review]
- Missing line breaks in install-on-citrix.md after line 58; double line break after line 62
- Outlook Add-in should be hyphenated in text. When not prefixed with 'Outlook', lowercase a.
- Missing link to next step in the 2 pages that replace deploy-on-citrix. Both at the end and after saying people can skip reading the page.
- ml-on-citrix: wrong level of subheadings in section *Web Extensions deployment* (don't skip from H2 to H4)
- ribbons-on-citrix: place registry script in an include
- ribbons-language applies to MailLink too, so no 'ribbons' in the file name. This should be a separate file that is linked to instead of included

**Comment by pavlas77** [comment]
@digitaldiina 

- Missing link to next step in the 2 pages that replace deploy-on-citrix. Both at the end and after saying people can skip reading the page.  - the original deploy-on-citrix didn't have the Previous / Next step as the whole Citrix deployment is optional and these steps are even more optional. Don't want to make some extra loops. Our consultants send these pages to IT admins as links, I think it is best to keep it without the steps. Onsite install is phased out slowly anyway.

- ribbons-on-citrix: place registry script in an include - don't understand this, there is a registry script specific for this page, not repeated elsewhere. Or did I misunderstood?

**Comment by digitaldiina** [comment]
@pavlas77 

- ok on the next step links
- we use includes also for larger pieces of code, even when not reused. It makes the content file cleaner, you can change the script without changing the content file, it's easier for ppl to grab the code file, and for example, for C# you can view the file with native highlighting and intelligence (to discover problems you don't see when embedded in the Markdown file.)

**Comment by pavlas77** [comment]
@digitaldiina  Registry code separated

**Comment by digitaldiina** [comment]
Thanks for your patience and multiple updates, @pavlas77 :)

**Pull request merged**
