### PR TITLE
#150 Pocket Tasks preference addded

### PR DESCRIPTION
**Pull request by pavlas77**

### CODE REVIEW

**Review by digitaldiina — CHANGES_REQUESTED** [review]
Could you:

- add so.version: 10.0.3 and so.date: 01.20.2022 to the header of the new file
- replace "Default value = 0, means no timeout." by adding " (no timeout)" behind the value 0 in the Default col
- remove space from "Pocket Tasks" in titles, seems like we use the prefsection string when listing these (see FieldLabels, DiaryView) Correct spacing will improve search.
- seems like the convention in the other files is to write YES and NO in caps in the Default col

**Comment by digitaldiina** [comment]
One other thing, @pavlas77, I noticed a misaligned column for DisplayDateFormatInLists in the Functions section. Would you be so kind to included that bug fix here?

**Comment by digitaldiina** [comment]
Why remove AssocHomeCountry? It is still in the API reference. Change in 10.0.5?

**Comment by pavlas77** [comment]
@digitaldiina Fixed. And reverted changes for the Associate section. I think it is not used but if it is still in the API, will eave it there.

**Comment by digitaldiina** [comment]
Great, thanks for the quick updates, @pavlas77

**Pull request merged**
