### PR TITLE
105 restructure setup guide onsite

### PR DESCRIPTION
**Pull request by pavlas77**

### CODE REVIEW

**Review by digitaldiina — CHANGES_REQUESTED** [review]
It is unclear where "Install NetServer / Web services" fits in the sequence and it does not have a prev/next/back to guide

**Comment by pavlas77** [comment]
> It is unclear where "Install NetServer / Web services" fits in the sequence and it does not have a prev/next/back to guide

Yes, that is correct and intentional. That is not part of the install sequence. It is an option during complicated deployment setup . It is used very seldom and if it is is part of the guide it will only look more complicated. Those who need it as skilled enough to find it in the menu under Web install.

**Comment by digitaldiina** [comment]
Then maybe a sentence/note in said file to de-confuse all those that do not need it? Do you do it instead of "Install SuperOffice Web"? What about the before-you-begin steps, do they apply to both sets of instructions?

**Comment by pavlas77** [comment]
It is more complicated, you can do it in paralel "install SuperOffice Web", and more then once, or you use a more complicated deployment scenario and install separate Netserver and Web. On the same server or different servers. That is described in the deployment scenarios. 

The before you begin steps are the same, yes.

The guide is for someone who doesnt know what to do, the advanced deployment scenarios are for skilled consultants, they dont follow the simple guide and dont need the prev / next steps.

Note to the Netserver guide added.

**Pull request merged**
